(function(g){var window=this;var Sua=function(a,b){var c=[];g.pm(b,function(a){var b;try{b=g.VD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.UD(b)&&c.push(a):c.push(a)},a);
return c},Tua=function(a,b){var c=Sua(a,b);
(0,g.H)(c,function(a){g.VD.prototype.remove.call(this,a)},a)},m9=function(a,b){g.zW.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.X=a;this.F={};this.V(a,"onMdxReceiversChange",this.H);this.V(a,"presentingplayerstatechange",this.H);this.H()},Uua=function(a){return a.H?a.F+((0,g.F)()-a.A)/1E3:a.F},Vua=function(){var a=g.wH;
Tua(a,a.g.Nd(!0))},n9=function(a){g.ZH.call(this,"ScreenServiceProxy");
this.Tc=a;this.o=[];this.o.push(this.Tc.$_s("screenChange",(0,g.A)(this.oQ,this)));this.o.push(this.Tc.$_s("onlineScreenChange",(0,g.A)(this.JM,this)))},o9=function(a){g.MH("cloudview",a)},Wua=function(a){o9("setApiReady_ "+a);
g.u("yt.mdx.remote.cloudview.apiReady_",a,void 0)},p9=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Xua=function(a){g.PG[a]&&(a=g.PG[a],(0,g.H)(a,function(a){g.NG[a]&&delete g.NG[a]}),a.length=0)},q9=function(){return g.x("yt.mdx.remote.connection_")},r9=function(a){g.u("yt.mdx.remote.connectData_",a,void 0)},Yua=function(a){g.u("yt.mdx.remote.currentScreenId_",a,void 0)},s9=function(){return g.x("yt.mdx.remote.currentScreenId_")},u9=function(){if(!t9){var a=g.x("yt.mdx.remote.screenService_");
t9=a?new n9(a):null}return t9},v9=function(a){g.u("yt.mdx.remote.cloudview.initializing_",a,void 0)},w9=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},x9=function(a){o9("setCastInstalled_ "+a);
g.yH("yt-remote-cast-installed",a)},y9=function(a){g.MH("cloudview",a)},Zua=function(a,b){p9().init(a,b)},z9=function(){return!!g.zH("yt-remote-cast-installed")},$ua=function(){o9("dispose");
var a=p9();a&&a.dispose();g.u("yt.mdx.remote.cloudview.instance_",null,void 0);Wua(!1);g.RG(A9);A9.length=0},ava=function(){var a=window.document.createElement("a");
g.Qd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Sa(a)},bva=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},cva=function(a){var b=g.MG();
if(b)if(b.clear(a),a)Xua(a);else for(var c in g.PG)Xua(c)},B9=function(){return g.x("yt.mdx.remote.channelParams_")||{}},D9=function(a){var b=q9();
r9(null);a||Yua("");g.u("yt.mdx.remote.connection_",a,void 0);C9&&((0,g.H)(C9,function(b){b(a)}),C9.length=0);
b&&!a?g.UG("yt-remote-connection-change",!1):!b&&a&&g.UG("yt-remote-connection-change",!0)},dva=function(){return g.x("yt.mdx.remote.connectData_")},E9=function(){var a=s9();
if(!a)return null;var b=u9().Sd();return g.YH(b,a)},eva=function(a,b){x9(!0);
v9(!1);Zua(a,function(a){a?(Wua(!0),g.SG("yt-remote-cast2-api-ready")):(y9("Failed to initialize cast API."),x9(!1),g.AH("yt-remote-cast-available"),g.AH("yt-remote-cast-receiver"),$ua());b(a)})},fva=function(){return z9()?p9()?p9().getCastSession():(y9("getCastSelector: Cast is not initialized."),null):(y9("getCastSelector: Cast API is not installed!"),null)},gva=function(){var a=ava(),b=window.document.getElementById(a),c=b&&g.LF(b,"loaded");
c||b&&!c||(b=bva(a,function(){g.LF(b,"loaded")||(g.MF(b,"loaded","true"),g.SG(a),g.eF(g.ya(cva,a),0))}))},hva=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},iva=function(){if(g.poa){var a=2,b=g.Fh(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Kh("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Hh,c)}},G9=function(a,b){s9();
E9()&&E9();Yua(a.id);var c=new g.cJ(F9,a,B9());c.connect(b,dva());c.subscribe("beforeDisconnect",function(a){g.UG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){q9()&&(q9(),D9(null))});
D9(c)},H9=function(){var a=g.dI();
if(!a)return null;var b=u9().Sd();return g.YH(b,a)},I9=function(a){g.MH("remote",a)},J9=function(){var a=q9();
return!!a&&3!=a.getProxyState()},K9=function(){w9()?p9().stopSession():y9("stopSession called before API ready.");
var a=q9();a&&(a.disconnect(1),D9(null))},jva=function(){var a;
a=u9().Tc.$_gos();var b=E9();b&&q9()&&(g.XH(a,b)||a.push(b));return hva(a)},M9=function(a,b){g.oG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.iC;this.A=this.o=null;this.H=(0,g.A)(this.SK,this);this.F=(0,g.A)(this.Ek,this);this.G=(0,g.A)(this.RK,this);this.J=(0,g.A)(this.fL,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.wt,this),kva(this))):c=3;0!=c&&(b?this.wt(c):g.eF((0,g.A)(function(){this.wt(c)},this),0));
var d=fva();d&&L9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},N9=function(a){return new g.SI(a.B.getPlayerContextData())},lva=function(a,b,c,d,e){var f=N9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.WI(f,b,d);g.t(c)&&(g.UI(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);O9(a,"setPlaylist",l);e||P9(a,f)},kva=function(a){(0,g.H)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.ya(this.dN,a),this))},a)},mva=function(a){(0,g.H)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},Q9=function(a,b){50>a.C.Cc()&&g.kC(a.C,b)},R9=function(a,b,c){var d=N9(a);
g.UI(d,c);-1E3!=d.g&&(d.g=b);P9(a,d)},O9=function(a,b,c){a.B.sendMessage(b,c)},P9=function(a,b){mva(a);
a.B.setPlayerContextData(g.XI(b));kva(a)},L9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.Ek(null));
a.A=b;a.A&&(S9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.Ek(a.A.media[0]))},nva=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=N9(a);b.contentId!=d.videoId&&S9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.UI(d,a.o.getEstimatedTime());P9(a,d)}else S9("No cast media video. Ignoring state update.")},S9=function(a){g.MH("CP",a)},T9=function(a,b,c){return(0,g.A)(function(a){this.ac("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.ac("Retrying "+b+" using MDx browser channel."),O9(this,b,c))},a)},ova=function(a){var b=!1;
p9()||(a=new g.MI(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.yH("yt-remote-cast-available",a);g.UG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){o9("onReceiverSelected: "+a.friendlyName);
g.yH("yt-remote-cast-receiver",a);g.UG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){o9("onReceiverResumed: "+a.friendlyName);
g.yH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){o9("onSessionChange: "+g.UH(a));
a||g.AH("yt-remote-cast-receiver");g.UG("yt-remote-cast2-session-change",a)}),g.u("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
o9("cloudview.createSingleton_: "+b);return b},pva=function(){var a=0<=g.Fb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.DG||a},U9=function(a,b){w9()?p9().setConnectedScreenStatus(a,b):y9("setConnectedScreenStatus called before ready.")},qva=function(){o9("clearCurrentReceiver");
g.AH("yt-remote-cast-receiver")},rva=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){iva();a({command:"cast.sender.init"});return}}if(window.chrome)if(iva(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.Dh();55<=b?a="55":50<=b&&(a="50");g.Kh("//www.gstatic.com/eureka/clank"+a+g.Ih,g.Hh)}else g.Lh(0);else g.Hh()},sva=function(a){a?(g.yH("yt-remote-session-app",a.app),g.yH("yt-remote-session-name",a.name)):(g.AH("yt-remote-session-app"),g.AH("yt-remote-session-name"));
g.u("yt.mdx.remote.channelParams_",a,void 0)},tva=function(){var a=B9();
if(g.Sb(a)){var a=g.cI(),b=g.zH("yt-remote-session-name")||"",c=g.zH("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.u("yt.mdx.remote.channelParams_",a,void 0)}},uva=function(){var a=H9();
a?(I9("Resume connection to: "+g.UH(a)),G9(a,0)):(g.lI(),qva(),I9("Skipping connecting because no session screen found."))},vva=function(a){I9("remote.onCastSessionChange_: "+g.UH(a));
if(a){var b=E9();b&&b.id==a.id?U9(b.id,"YouTube TV"):(b&&K9(),G9(a,1))}else q9()&&K9()},wva=function(){var a=jva(),b=E9();
b||(b=H9());return g.$a(a,function(a){return b&&g.RH(b,a.key)?!0:!1})},xva=function(){var a=g.zH("yt-remote-cast-receiver");
return a?a.friendlyName:null},yva=function(a,b,c,d){pva()?ova(b)&&(v9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?eva(a,c):(window.__onGCastApiAvailable=function(b,d){b?eva(a,c):(y9("Failed to load cast API: "+d),x9(!1),v9(!1),g.AH("yt-remote-cast-available"),g.AH("yt-remote-cast-receiver"),$ua(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):gva():rva())):o9("Cannot initialize because not running Chrome")},
zva=function(a){this.port=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.yg(a)||"";b&&(this.port=":"+b);this.A=g.xg(a)||"";a=g.Fb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ra(a,"10.0")&&(this.o=!1))},V9=function(a){g.X.call(this,{K:"div",
Y:"ytp-remote",R:[{K:"div",Y:"ytp-remote-display-status",R:[{K:"div",Y:"ytp-remote-display-status-icon",R:[g.BE()]},{K:"div",Y:"ytp-remote-display-status-text",R:["{{statustext}}"]},{K:"div",Y:"ytp-remote-display-status-receiver",R:["{{receiver}}"]}]}]});this.g=new g.$V(this,250);g.M(this,this.g);this.A=a;this.V(a,"presentingplayerstatechange",this.B);Ava(this,g.zV(a))},Ava=function(a,b){if(3==a.A.Xa()){var c;
c=g.W(b,128)?g.U("YTP_MDX_STATUS_ERROR"):b.qb()||g.W(b,4)?g.U("YTP_MDX_STATUS_PLAYING"):g.U("YTP_MDX_STATUS_CONNECTED");var d=a.A.Vc("remote","currentReceiver");a.update({statustext:c,receiver:d.name});a.g.show()}else g.bW(a.g)},W9=function(a,b,c){g.L.call(this);
this.H=a;this.X=b;b.addEventListener("onVolumeChange",this.Dn,this);b.addEventListener("onCaptionsTrackListChanged",this.oz,this);b.addEventListener("captionschanged",this.bz,this);b.addEventListener("captionssettingschanged",this.Gs,this);b.addEventListener("videoplayerreset",this.Hk,this);b.addEventListener("mdxautoplaycancel",this.Yu,this);this.C=!1;this.g=c;c.subscribe("proxyStateChange",this.Dz,this);c.subscribe("remotePlayerChange",this.Gk,this);c.subscribe("remoteQueueChange",this.Hk,this);
c.subscribe("autoplayUpNext",this.Zy,this);c.subscribe("previousNextChange",this.Az,this);c.subscribe("nowAutoplaying",this.rz,this);c.subscribe("autoplayDismissed",this.Yy,this);this.suggestion=null;this.D=new g.pR(64);this.o=new g.ku(this.NA,500,this);g.M(this,this.o);this.A=new g.ku(this.OA,1E3,this);g.M(this,this.A);this.B={};this.G=new g.ku(this.cB,1E3,this);g.M(this,this.G);this.F=new g.uk(this.hS,1E3,this);g.M(this,this.F);this.J=g.y;this.Gs();this.Hk();this.Gk()},X9=function(a,b){var c=a.H,
d=a.X.getVideoData().lengthSeconds;
c.H=b||0;c.g.U("progresssync",b,d)},Bva=function(a){X9(a,0);
a.o.stop();Y9(a,new g.pR(64))},a$=function(a,b){if(Z9(a)&&!a.C){var c=null;
b&&(c={style:a.X.kl()},g.$b(c,b));a.g.HA($9(a),c);a.B=N9(a.g).o}},b$=function(a,b){var c=a.X.Xf();
c?lva(a.g,$9(a),b,c.Qd(),c.listId.toString()):lva(a.g,$9(a),b);Y9(a,new g.pR(1))},Cva=function(a,b){if(b){var c=a.X.Vc("captions","tracklist",{xx:1});
c&&c.length?(a.X.Fe("captions","track",b),a.C=!1):(a.X.dl("captions"),a.C=!0)}else a.X.Fe("captions","track",{})},Z9=function(a){return N9(a.g).videoId==$9(a)},$9=function(a){return a.X.getVideoData().videoId},Y9=function(a,b){a.A.stop();
var c=a.D;if(!g.vR(c,b)){var d=g.W(b,2);if(d!=g.W(a.D,2)){var e=a.X;(e=g.yV(e.app,e.playerType||1))&&g.wU(e,d)}a.D=b;Dva(a.H,c,b)}},c$=function(){var a=wva();
!a&&z9()&&xva()&&(a={key:"cast-selector-receiver",name:xva()});return a},Eva=function(){var a=jva();
z9()&&g.zH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Fva=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.wH&&Vua();g.fI();F9||(F9=new zva,g.nI()&&(F9.g="/api/loungedev"));C9||(C9=g.x("yt.mdx.remote.deferredProxies_")||[],g.u("yt.mdx.remote.deferredProxies_",C9,void 0));tva();var c=u9();if(!c){var d=new g.yI(F9);g.u("yt.mdx.remote.screenService_",d,void 0);c=u9();yva(a,d,function(a){a?s9()&&U9(s9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.UG("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.x("yt.mdx.remote.initialized_")&&
(g.u("yt.mdx.remote.initialized_",!0,void 0),I9("Initializing: "+g.Lc(b)),d$.push(g.QG("yt-remote-cast2-availability-change",function(){g.UG("yt-remote-receiver-availability-change")})),d$.push(g.QG("yt-remote-cast2-receiver-selected",function(){r9(null);
g.UG("yt-remote-auto-connect","cast-selector-receiver")})),d$.push(g.QG("yt-remote-cast2-receiver-resumed",function(){g.UG("yt-remote-receiver-resumed","cast-selector-receiver")})),d$.push(g.QG("yt-remote-cast2-session-change",vva)),d$.push(g.QG("yt-remote-connection-change",function(a){a?U9(s9(),"YouTube TV"):H9()||(U9(null,null),qva())})),a=B9(),b.isAuto&&(a.id+="#dial"),g.uG("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,I9(" -- with channel params: "+g.Lc(a)),
sva(a),c.start(),s9()||uva())},e$=function(){z9()?p9()?w9()?(o9("Requesting cast selector."),p9().requestSession()):(o9("Wait for cast API to be ready to request the session."),A9.push(g.QG("yt-remote-cast2-api-ready",e$))):y9("requestCastSelector: Cast is not initialized."):y9("requestCastSelector: Cast API is not installed!")},f$=function(a){g.WV.call(this,a);
this.A={key:g.WH(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.pR(64);this.H=0;var b=g.sV(a).C;b&&(b=b.A&&b.A.g)&&(b=new m9(a,b),g.M(this,b));b=new V9(a);g.M(this,b);g.QV(a,b.element,5)},Dva=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.oU(c,b))},g$=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)K9();
else{a.B=b;var c;c=a.g.getPlaylistId();var d=a.g.getVideoData().videoId;if(c||d){var e,f=a.g.Xf();if(f){e=[];for(var k=0;k<f.getLength();k++)e[k]=f.Xb(k).videoId}else e=[a.g.getVideoData().videoId];c={videoIds:e,listId:c,videoId:d,index:Math.max(a.g.AB(),0),currentTime:a.g.getCurrentTime()}}else c=null;I9("Connecting to: "+g.Lc(b));"cast-selector-receiver"==b.key?(r9(c||null),c=c||null,w9()?p9().setLaunchParams(c):y9("setLaunchParams called before ready.")):!c&&J9()&&s9()==b.key?g.UG("yt-remote-connection-change",
!0):(K9(),r9(c||null),c=u9().Sd(),(c=g.YH(c,b.key))&&G9(c,1))}};
g.p(m9,g.zW);m9.prototype.H=function(){var a=this.X.Vc("remote","receivers");a&&1<a.length&&!this.X.Vc("remote","quickCast")?(this.F=g.Bb(a,this.B,this),g.BW(this,(0,g.J)(a,this.B)),a=this.X.Vc("remote","currentReceiver"),g.AW(this,this.B(a)),this.enable(!0)):this.enable(!1)};
m9.prototype.B=function(a){return a.key};
m9.prototype.Me=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
m9.prototype.fd=function(a){g.zW.prototype.fd.call(this,a);this.X.Fe("remote","currentReceiver",this.F[a]);this.A.Ub()};
g.C(n9,g.ZH);g.h=n9.prototype;g.h.Sd=function(a){return this.Tc.$_gs(a)};
g.h.contains=function(a){return!!this.Tc.$_c(a)};
g.h.get=function(a){return this.Tc.$_g(a)};
g.h.start=function(){this.Tc.$_st()};
g.h.zo=function(a,b,c){this.Tc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Tc.$_r(a,b,c)};
g.h.no=function(a,b,c,d){this.Tc.$_un(a,b,c,d)};
g.h.P=function(){for(var a=0,b=this.o.length;a<b;++a)this.Tc.$_ubk(this.o[a]);this.o.length=0;this.Tc=null;n9.O.P.call(this)};
g.h.oQ=function(){this.U("screenChange")};
g.h.JM=function(){this.U("onlineScreenChange")};
var t9=null,A9=[],C9=null,F9=null;g.C(M9,g.oG);g.h=M9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,T9(this,"play")):O9(this,"play"),R9(this,1,g.VI(N9(this))),this.U("remotePlayerChange")):Q9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,T9(this,"pause")):O9(this,"pause"),R9(this,2,g.VI(N9(this))),this.U("remotePlayerChange")):Q9(this,this.pause)};
g.h.oB=function(a){if(1==this.g){if(this.o){var b=N9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.qb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,T9(this,"seekTo",{newTime:a}))}else O9(this,"seekTo",{newTime:a});R9(this,3,a);this.U("remotePlayerChange")}else Q9(this,g.ya(this.oB,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,T9(this,"stopVideo")):O9(this,"stopVideo");var a=N9(this);a.index=-1;a.videoId="";g.TI(a);P9(this,a);this.U("remotePlayerChange")}else Q9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=N9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.A)(function(){S9("set receiver volume: "+d)},this),(0,g.A)(function(){this.ac("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.A)(function(){S9("set receiver muted: "+b)},this),(0,g.A)(function(){this.ac("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);O9(this,"setVolume",e)}c.muted=b;c.volume=a;P9(this,c)}else Q9(this,g.ya(this.setVolume,a,b))};
g.h.HA=function(a,b){if(1==this.g){var c=N9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Lc(b.style),g.$b(d,c.o));O9(this,"setSubtitlesTrack",d);P9(this,c)}else Q9(this,g.ya(this.HA,a,b))};
g.h.vt=function(a,b){if(1==this.g){O9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Kc.id});var c=N9(this);c.audioTrackId=b.Kc.id;P9(this,c)}else Q9(this,g.ya(this.vt,a,b))};
g.h.nB=function(a,b){if(1==this.g){if(a&&b){var c=N9(this);g.WI(c,a,b);P9(this,c)}O9(this,"previous")}else Q9(this,g.ya(this.nB,a,b))};
g.h.mB=function(a,b){if(1==this.g){if(a&&b){var c=N9(this);g.WI(c,a,b);P9(this,c)}O9(this,"next")}else Q9(this,g.ya(this.mB,a,b))};
g.h.Nv=function(){1==this.g?O9(this,"dismissAutoplay"):Q9(this,this.Nv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}M9.O.dispose.call(this)};
g.h.P=function(){mva(this);this.B=null;this.C.clear();L9(this,null);M9.O.P.call(this)};
g.h.wt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.lC(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.dN=function(a,b){this.U(a,b)};
g.h.SK=function(a){if(!a)this.Ek(null),L9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=N9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)S9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,P9(this,b)}};
g.h.Ek=function(a){S9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),nva(this),this.U("remotePlayerChange")};
g.h.RK=function(a){a?(nva(this),this.U("remotePlayerChange")):this.Ek(null)};
g.h.fL=function(){var a=fva();a&&L9(this,a)};
g.h.ac=function(a){g.MH("CP",a)};
var d$=[];g.h=zva.prototype;g.h.Jh=function(a,b,c){var d=this.g;if(g.t(c)?c:this.o)d="https://"+this.A+this.port+this.g;return g.Gg(d+a,b||{})};
g.h.ut=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Jb:g.ya(this.jQ,c,!0),onError:g.ya(this.iQ,d),ed:g.ya(this.kQ,d)};b&&(c.Nb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.rF(a,c)};
g.h.jQ=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.iQ=function(a,b){a(Error("Request error: "+b.status))};
g.h.kQ=function(a){a(Error("request timed out"))};
g.p(V9,g.X);V9.prototype.B=function(a){Ava(this,a.state)};
g.C(W9,g.L);g.h=W9.prototype;
g.h.P=function(){W9.O.P.call(this);this.o.stop();this.A.stop();this.J();this.X.removeEventListener("onVolumeChange",this.Dn,this);this.X.removeEventListener("onCaptionsTrackListChanged",this.oz,this);this.X.removeEventListener("captionschanged",this.bz,this);this.X.removeEventListener("videoplayerreset",this.Hk,this);this.X.removeEventListener("captionssettingschanged",this.Gs,this);this.X.removeEventListener("mdxautoplaycancel",this.Yu,this);this.g.unsubscribe("proxyStateChange",this.Dz,this);this.g.unsubscribe("remotePlayerChange",
this.Gk,this);this.g.unsubscribe("remoteQueueChange",this.Hk,this);this.g.unsubscribe("autoplayUpNext",this.Zy,this);this.g.unsubscribe("previousNextChange",this.Az,this);this.g.unsubscribe("nowAutoplaying",this.rz,this);this.g.unsubscribe("autoplayDismissed",this.Yy,this);this.g=this.H=null};
g.h.dC=function(a,b){2==this.g.g||(Z9(this)?this.FG.apply(this,arguments):this.BG.apply(this,arguments))};
g.h.bz=function(a){this.dC("control_subtitles_set_track",g.Sb(a)?null:a)};
g.h.Gs=function(){var a=this.X.Vc("captions","track");g.Sb(a)||a$(this,a)};
g.h.BG=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":b$(this,this.X.getCurrentTime());break;case "control_seek":b$(this,c[0]);break;case "control_subtitles_set_track":a$(this,c[0]);break;case "control_set_audio_track":c=c[0],Z9(this)&&this.g.vt($9(this),c)}};
g.h.FG=function(a,b){if(1081!=N9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":N9(this.g).qb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.Mi(c[0],c[1]);break;case "control_subtitles_set_track":a$(this,c[0]);break;case "control_set_audio_track":c=c[0],Z9(this)&&this.g.vt($9(this),c)}}};
g.h.Dn=function(a){if(Z9(this)){this.g.unsubscribe("remotePlayerChange",this.Gk,this);var b=Math.round(a.volume);a=!!a.muted;var c=N9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.Gk,this)}};
g.h.oz=function(){g.Sb(this.B)||Cva(this,this.B);this.C=!1};
g.h.Dz=function(a,b){this.A.stop();2==b&&this.OA()};
g.h.Gk=function(){if(Z9(this)){this.o.stop();var a=N9(this.g);switch(a.g){case 1081:Y9(this,new g.pR(8));break;case 1:this.NA();Y9(this,new g.pR(8));break;case 1083:case 3:Y9(this,new g.pR(9));break;case 0:Y9(this,new g.pR(2));this.F.stop();X9(this,this.X.getVideoData().lengthSeconds);break;case 1082:Y9(this,new g.pR(4));break;case 2:Y9(this,new g.pR(4));X9(this,g.VI(a));break;case -1:Y9(this,new g.pR(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},Y9(this,
new g.pR(128,a))}var a=N9(this.g).o,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,Cva(this,a));a=N9(this.g);-1==a.volume||Math.round(this.X.getVolume())==a.volume&&this.X.De()==a.muted||this.G.isActive()||this.cB()}else Bva(this)};
g.h.Az=function(){this.X.U("mdxpreviousnextchange")};
g.h.Hk=function(){Z9(this)||Bva(this)};
g.h.Yu=function(){this.g.Nv()};
g.h.Zy=function(a){a&&(a=g.rF("/watch_queue_ajax",{method:"GET",Fc:{action_get_watch_queue_item:1,video_id:a},Jb:(0,g.A)(this.eO,this)}))&&(this.J=(0,g.A)(a.abort,a))};
g.h.eO=function(a,b){var c=new g.GQ({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.X.U("mdxautoplayupnext",c)};
g.h.rz=function(a){(0,window.isNaN)(a)||this.X.U("mdxnowautoplaying",a)};
g.h.Yy=function(){this.X.U("mdxautoplaycanceled")};
g.h.hS=function(a,b){-1==N9(this.g).g?b$(this,a):b&&this.g.oB(a)};
g.h.cB=function(){if(Z9(this)){var a=N9(this.g);this.X.removeEventListener("onVolumeChange",this.Dn,this);a.muted?this.X.mute():this.X.zg();this.X.setVolume(a.volume);this.X.addEventListener("onVolumeChange",this.Dn,this)}};
g.h.NA=function(){this.o.stop();if(!this.g.la()){var a=N9(this.g);a.qb()&&Y9(this,new g.pR(8));X9(this,g.VI(a));this.o.start()}};
g.h.OA=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};
g.C(f$,g.WV);g.h=f$.prototype;g.h.create=function(){Fva("embedded"==g.Y(this.g).g);this.D.push(g.QG("yt-remote-before-disconnect",this.OK,this));this.D.push(g.QG("yt-remote-connection-change",this.nN,this));this.D.push(g.QG("yt-remote-receiver-availability-change",this.Bz,this));this.D.push(g.QG("yt-remote-auto-connect",this.lN,this));this.D.push(g.QG("yt-remote-receiver-resumed",this.kN,this));this.Bz()};
g.h.load=function(){this.g.Ip();f$.O.load.call(this);this.C=new W9(this,this.g,this.o);var a;a=(a=dva())?a.currentTime:0;var b=J9()?new M9(q9(),void 0):null;0==a&&b&&(a=g.VI(N9(b)));0!=a&&(this.H=a||0,this.g.U("progresssync",a,void 0));Dva(this,this.F,this.F);g.M2(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.Ve(this.C,this.o);this.o=this.C=null;f$.O.unload.call(this);g.M2(this.g.app,5)};
g.h.P=function(){g.RG(this.D);f$.O.P.call(this)};
g.h.pl=function(a,b){this.loaded&&this.C.dC.apply(this.C,arguments)};
g.h.gG=function(){return this.loaded?this.C.suggestion:null};
g.h.Af=function(){return this.o?N9(this.o).Af:!1};
g.h.hasNext=function(){return this.o?N9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.MR=function(){var a=N9(this.o),b=this.g.getVideoData(),c=this.g.Dd(),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.B+((0,g.F)()-a.A)/1E3:a.B;var l=1>=Uua(a)-this.getCurrentTime(),m=a.J,n=Uua(a),a=0<a.C?a.C+((0,g.F)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.NR=function(){this.o&&this.o.mB()};
g.h.OR=function(){this.o&&this.o.nB()};
g.h.OK=function(a){1==a&&(this.J=this.o?N9(this.o):null)};
g.h.nN=function(){var a=J9()?new M9(q9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Ue(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.xB(a.videoId,g.VI(a)));this.g.U("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.Bz=function(){this.G=[this.A].concat(Eva());var a=c$()||this.A;g$(this,a);this.g.ya("onMdxReceiversChange")};
g.h.lN=function(){var a=c$();g$(this,a)};
g.h.kN=function(){this.B=c$()};
g.h.LR=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?e$():g$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&e$(),!0):!1}};
g.h.PR=function(){O9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.ze=function(){return!1};
window._exportCheck==g.Aa&&g.u("ytmod.player.remote",f$,void 0);})(_yt_player);
